dist: disco
sudo: required
language: c
compiler:
  - gcc
  - clang
script:
  - mkdir Release
  - cd Release
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make && ctest --verbose
before_install:
  - sudo apt-get install libmariadb-dev cmake libssl-dev libc6-dev zlib1g-dev libconfig-dev
