sudo: required
language: c
dist: focal
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script:
  - docker-compose up -d --build
after_script:
  - docker-compose down
script:
  - docker-compose exec -e COMPILE_ONLY="1" -e PRODUCTION="1" sys sh -c "/home/libnss-maria/scripts/compile_and_test.sh"
env:
  - DISTRO="debian"
  - DISTRO="ubuntu"
  - DISTRO="ubuntu-lts"
  - DISTRO="centos"
  - DISTRO="fedora"
  - DISTRO="archlinux"
