dist: eoan
sudo: required
language: c
compiler:
  - gcc
  - clang
script:
  - mkdir Release
  - cd Release
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest --verbose
before_install:
  - sudo apt-get install -y build-essential cmake libmariadb-dev libconfig-dev syslog-ng-dev bats
  - sudo apt-get install -y syslog-ng mariadb-client libconfig9 mariadb-server ruby pkg-config
