sudo: required
language: c
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script:
  - docker-compose up -d --build
after_script:
  - docker-compose down
script:
  - docker-compose exec sys sh -c "/home/libnss-maria/script/compile_in_vagrant.sh"
