sudo: required
language: c
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script:
  - docker-compose up -d --build
after_script:
  - docker-compose down
script:
  - docker exec -it libnss-maria_sys_1 sh -c "./script/compile_in_vagrant.sh"
