version: '3'
services:
  sys:
    build:
      context: .
      dockerfile: Dockerfile
    image: debian:buster
    volumes:
      - ${TRAVIS_BUILD_DIR}:/home/libnss-maria
    stdin_open: true
    tty: true
    command: /bin/bash
    links:
      - database
  database:
    image: library/mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'
